# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bf35496b18d1417430bc6a16b08258677b4106be58ac3604673a242ba129cd4c681009fe75df6eea1624421f045dbb9b82704eb316fc92715a0b4cc4b38a803

test:
  secret_key_base: da91784f6ef89cbfc12292ddfff84d53b5e78804c3e1bfdcdd6ad8d1ad58dcd01c12900e8787d123c053e2c13a58f93a1fbe84f5244b07e4951a1b7bc74a99f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
